# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Toolkit < Formula
  desc "My opinionated toolkit"
  homepage "https://github.com/kjuulh/toolkit"
  url "https://github.com/kjuulh/toolkit/archive/v0.1.1.tar.gz"
  sha256 "898cf82ce1e4fbc71d74ff1c177345d9e9fb3dd2cd75691eafa5a42ebd006f30"
  license "NOASSERTION"

  on_macos do
    on_intel do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.1.1/toolkit-0.1.1-darwin-amd64.tar.gz"
      sha256 "fa7f2d9282dcce433e2894658c8b09777d2df4c4f9851a83e55f6fec0faae5b0"
    end

    on_arm do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.1.1/toolkit-0.1.1-darwin-arm64.tar.gz"
      sha256 "10b18604df5d8d66d9191351483524b11696799be7342d350aa46217f39a8042"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.1.1/toolkit-0.1.1-linux-amd64.tar.gz"
      sha256 "31dc70374833e05fd378b7ea195dc8ad6e4ae698f09b2e07408ad612bd4c31e6"
    end

    on_arm do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.1.1/toolkit-0.1.1-linux-arm64.tar.gz"
      sha256 "25caf2fd963db0f8554d7d5ba28413f0c796773d8680c8ae2c5decea43f27f38"
    end
  end

  def install
    bin.install "toolkit"
  end
end
