# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuzzyClone < Formula
  desc "Fuzzy clone is a fuzzy repository picker and downloader, it allows you to quickly jump between repositories you contribute to, whether you have them downloaded or not."
  homepage "https://kasperhermansen.com"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.7/fuzzy-clone-darwin-amd64", using: CurlDownloadStrategy
      sha256 "17ab01983d4ee90924d5eccaca1ae52606dfe8883581733aae1d2efbf2e2cc0c"

      def install
        bin.install "fuzzy-clone-darwin-amd64" => "fuzzy-clone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.7/fuzzy-clone-darwin-arm64", using: CurlDownloadStrategy
      sha256 "85a382f2668651f8d98c14efa5eeb2682cf5a65cf31510b47194ebcf93ccbdac"

      def install
        bin.install "fuzzy-clone-darwin-arm64" => "fuzzy-clone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.7/fuzzy-clone-linux-amd64", using: CurlDownloadStrategy
      sha256 "1e3dd53f5dbfc1c0bd0229906f656dae5ddb8bef87ce41e180a8df8263b7a1a1"

      def install
        bin.install "fuzzy-clone-linux-amd64" => "fuzzy-clone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.7/fuzzy-clone-linux-arm64", using: CurlDownloadStrategy
      sha256 "23e5ced10d699f6968a2c7443447e38df1101e4ff65c113a0a42bb2fa8e56f92"

      def install
        bin.install "fuzzy-clone-linux-arm64" => "fuzzy-clone"
      end
    end
  end

  def caveats
    <<~EOS
      Run either fuzzy-clone directory or

      # zsh
      echo 'eval "$(fuzzy-clone init zsh)"' >> ~/.zshrc

      fz # to search for repos
    EOS
  end

  test do
    system "#{bin}/fuzzy-clone --version"
  end
end
