# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuzzyClone < Formula
  desc "Fuzzy clone is a fuzzy repository picker and downloader, it allows you to quickly jump between repositories you contribute to, whether you have them downloaded or not."
  homepage "https://kasperhermansen.com"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.5/fuzzy-clone-darwin-amd64", using: CurlDownloadStrategy
      sha256 "29f37cb97fe10bc1fb6d169560507eefeb4b658c807b8275868dd4a34e23414d"

      def install
        bin.install "fuzzy-clone-darwin-amd64" => "fuzzy-clone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.5/fuzzy-clone-darwin-arm64", using: CurlDownloadStrategy
      sha256 "b68ed972f5b0a2c1356f0419d3abe24631983da44c15e19e6195f537c25a707b"

      def install
        bin.install "fuzzy-clone-darwin-arm64" => "fuzzy-clone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.5/fuzzy-clone-linux-arm64", using: CurlDownloadStrategy
      sha256 "de9c94329bf55811faf703b6366c3d55aca5187121a6c6021e2cde465c3288ba"

      def install
        bin.install "fuzzy-clone-linux-arm64" => "fuzzy-clone"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.5/fuzzy-clone-linux-amd64", using: CurlDownloadStrategy
      sha256 "4b6e44c6841dc55186830ca436cd5b2fc6ba99558c7713346820477fd6ee9595"

      def install
        bin.install "fuzzy-clone-linux-amd64" => "fuzzy-clone"
      end
    end
  end

  def caveats
    <<~EOS
      Run either fuzzy-clone directory or

      # zsh
      echo 'eval "$(fuzzy-clone init zsh)"' >> ~/.zshrc

      fz # to search for repos
    EOS
  end

  test do
    system "#{bin}/fuzzy-clone --version"
  end
end
