# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Toolkit < Formula
  desc "My opinionated toolkit"
  homepage "https://github.com/kjuulh/toolkit"
  url "https://github.com/kjuulh/toolkit/archive/v0.2.0.tar.gz"
  sha256 "c5e134d53096e59fef7bb7e4f2d1f9966cd51cae8ad78aa55ce7ecdf790a0bb7"
  license "NOASSERTION"

  depends_on "bandwhich"
  depends_on "bottom"
  depends_on "dust"
  depends_on "fzf"
  depends_on "gh"
  depends_on "procs"
  depends_on "sourcegraph/src-cli/src-cli"
  depends_on "tokei"

  on_macos do
    on_intel do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.2.0/toolkit-0.2.0-darwin-amd64.tar.gz"
      sha256 "12395a2ad8f8c118423542f0094e0749baaf66ab2158db689e737e370edb9b26"
    end

    on_arm do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.2.0/toolkit-0.2.0-darwin-arm64.tar.gz"
      sha256 "a452e2244fc0a17c16ef23ff1deb6e721b2a9856539bb955bf25a6b141b7df73"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.2.0/toolkit-0.2.0-linux-amd64.tar.gz"
      sha256 "9a2a021b71901e0f6e617fbf42bd9c2b8421fb906604e1ab02d4fa47ebbae2ee"
    end

    on_arm do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.2.0/toolkit-0.2.0-linux-arm64.tar.gz"
      sha256 "f1c6c69bb22b667c2dd9db629d05260ee8b6fde83dd37124dda30246e7a58455"
    end
  end

  def install
    bin.install "toolkit"
  end
end
