# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Toolkit < Formula
  desc "My opinionated toolkit"
  homepage "https://github.com/kjuulh/toolkit"
  url "https://github.com/kjuulh/toolkit/archive/v0.1.17.tar.gz"
  sha256 "1a5312f938947eaa7c6e4e69f1252264b357ca53adb71666b286b33980afd600"
  license "NOASSERTION"

  depends_on "bandwhich"
  depends_on "bottom"
  depends_on "dust"
  depends_on "fzf"
  depends_on "gh"
  depends_on "procs"
  depends_on "sourcegraph/src-cli/src-cli"
  depends_on "tokei"

  on_macos do
    on_intel do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.1.17/toolkit-0.1.17-darwin-amd64.tar.gz"
      sha256 "6d87e4a134cfc40f3737e06fa626fbc180acff87142947fb1e7cce4f2402c13a"
    end

    on_arm do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.1.17/toolkit-0.1.17-darwin-arm64.tar.gz"
      sha256 "8b07178fce0332e1f9dd594efbfeae4880671af57d0bf7699ba6446a44b744e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.1.17/toolkit-0.1.17-linux-amd64.tar.gz"
      sha256 "e802e73b2faee8b0798df1b8d1e58b1b95c39927dbf05a511ad0a8ff2e19bc8a"
    end

    on_arm do
      url "https://github.com/kjuulh/toolkit/releases/download/v0.1.17/toolkit-0.1.17-linux-arm64.tar.gz"
      sha256 "dd85c2e9e81674592622c9c8e87da6f78467e04a4e6f9cb8482eb80c851ec9e5"
    end
  end

  def install
    bin.install "toolkit"
  end
end
